/* BANCO DE QUESTÕES INTEGRAL - 200 QUESTÕES
   Técnico em Automação Industrial (SENAI-SP)
   Unidades: TI, Fundamentos, Programação (Arduino) e Instalação
*/

// CONFIGURAÇÕES DA AVALIAÇÃO
const examConfig = {
    title: "Avaliação Diagnóstica - 3º Semestre",
    maxPenalties: 10,
    timeLimitMinutes: 90,
    lockoutDurationMinutes: 60,
    questionsQty: 40, 
    difficultyDistribution: {
        easy: 30,
        medium: 40,
        hard: 30
    }
};

// CHAVE MESTRA DAS RESPOSTAS
// Mapeamento: a=0, b=1, c=2, d=3
const _k = "bcacbdccbcbbcbbcbcbccbccbbacbcbabcbcbbcbcbbbbbccbbcbbbccbbcacabcbcbbabcbcbbabbbabbaabbbcbbbbabbbbbbaacbcbdccbcbbcbbcbcbccbccbbacbcbabcbcbbcbcbbbbbccbbcbbbccbbcacabcbcbbabcbcbbabbbabbaabbbcbbbbabbbbbba";

const fullQuestionBank = [
    { "id": 0, "difficulty": "easy", "q": "Qual o principal objetivo da Indústria 4.0?", "options": ["Aumento da mão de obra manual", "Digitalização e integração de processos", "Uso exclusivo de máquinas a vapor", "Redução da segurança digital"] },
    { "id": 1, "difficulty": "easy", "q": "O que caracteriza a 'Virtualização' na Indústria 4.0?", "options": ["Cópia física de documentos", "Criação de uma cópia virtual da fábrica através de sensores", "Uso de papéis para monitoramento", "Desligamento de computadores"] },
    { "id": 2, "difficulty": "easy", "q": "No hardware, qual a função da memória RAM?", "options": ["Armazenar dados permanentemente", "Armazenamento temporário para processamento rápido", "Resfriar o processador", "Converter energia AC em DC"] },
    { "id": 3, "difficulty": "medium", "q": "Qual das opções abaixo é uma tecnologia habilitadora da Indústria 4.0?", "options": ["Prensa manual", "Big Data e Analytics", "Máquina de escrever", "Correia dentada simples"] },
    { "id": 4, "difficulty": "medium", "q": "O que é 'Cloud Computing'?", "options": ["Computação em nuvem (servidores remotos)", "Previsão do tempo industrial", "Resfriamento de data centers", "Cabos de rede subterrâneos"] },
    { "id": 5, "difficulty": "hard", "q": "Qual a principal vulnerabilidade em redes Wi-Fi industriais?", "options": ["Falta de cabos", "Interceptação de dados sem criptografia", "Excesso de sinal", "Cor da antena"] },
    { "id": 6, "difficulty": "easy", "q": "No Excel, qual função soma um intervalo de células?", "options": ["=MEDIA()", "=SOMA()", "=CONTAR()", "=SE()"] },
    { "id": 7, "difficulty": "medium", "q": "O que é 'Interoperabilidade'?", "options": ["Capacidade de sistemas operarem de forma isolada", "Capacidade de diversos sistemas se comunicarem e trabalharem juntos", "Troca física de peças", "Aumento de custos de manutenção"] },
    { "id": 8, "difficulty": "medium", "q": "O termo 'Cybersecurity' refere-se a:", "options": ["Segurança física da portaria", "Proteção de sistemas e dados contra ataques digitais", "Manutenção de motores", "Instalação de câmeras analógicas"] },
    { "id": 9, "difficulty": "easy", "q": "Qual dispositivo mobile é comumente usado para leitura de manuais em campo?", "options": ["Servidor rack", "Tablet", "Impressora 3D", "Desktop"] },
    { "id": 10, "difficulty": "hard", "q": "O que define a 'Descentralização' na fábrica inteligente?", "options": ["Decisões tomadas apenas pela diretoria", "Sistemas ciberfísicos tomam decisões autónomas", "Uso de um único computador central", "Redução do número de máquinas"] },
    { "id": 11, "difficulty": "easy", "q": "Qual extensão de arquivo é padrão para planilhas eletrónicas?", "options": [".docx", ".xlsx", ".pdf", ".jpg"] },
    { "id": 12, "difficulty": "medium", "q": "O que é 'Inteligência Artificial'?", "options": ["Uso de robôs pneumáticos", "Sistemas que simulam capacidades humanas de aprendizado", "Aumento da potência elétrica", "Sensores de presença simples"] },
    { "id": 13, "difficulty": "medium", "q": "Na segurança digital, um 'Firewall' serve para:", "options": ["Apagar incêndios", "Filtrar o tráfego de rede e bloquear acessos não autorizados", "Aumentar a velocidade da internet", "Formatar o disco rígido"] },
    { "id": 14, "difficulty": "medium", "q": "O que é 'Manufatura Aditiva'?", "options": ["Subtração de material", "Impressão 3D", "Fundição tradicional", "Montagem manual"] },
    { "id": 15, "difficulty": "easy", "q": "No Windows, qual atalho alterna entre janelas abertas?", "options": ["Ctrl + C", "Alt + Tab", "Ctrl + V", "F5"] },
    { "id": 16, "difficulty": "medium", "q": "O termo 'IoT' significa:", "options": ["Indústria de Transmissão", "Internet das Coisas", "Integração de Operação", "Internacionalização Técnica"] },
    { "id": 17, "difficulty": "easy", "q": "Qual a função do Sistema Operacional?", "options": ["Gerar eletricidade", "Gerenciar o hardware e fornecer interface ao usuário", "Apenas navegar na internet", "Criar desenhos técnicos"] },
    { "id": 18, "difficulty": "medium", "q": "O que é um 'Software Open Source'?", "options": ["Software muito caro", "Software com código-fonte aberto e gratuito", "Software que não precisa de computador", "Software de uso militar apenas"] },
    { "id": 19, "difficulty": "hard", "q": "Na Indústria 4.0, 'Sistemas Ciberfísicos' são:", "options": ["Apenas robôs físicos", "Integração entre computação, redes e processos físicos", "Apenas simulações em computador", "Manual de instruções em papel"] },
    { "id": 20, "difficulty": "medium", "q": "O que é 'Phishing'?", "options": ["Pesca esportiva", "Técnica de enganar usuários para roubar senhas", "Aceleração do processador", "Upgrade de memória"] },
    { "id": 21, "difficulty": "easy", "q": "Qual dispositivo é um periférico de entrada?", "options": ["Monitor", "Teclado", "Impressora", "Caixa de som"] },
    { "id": 22, "difficulty": "medium", "q": "No PowerPoint, para que serve o 'Slide Mestre'?", "options": ["Apresentar o slide final", "Definir o padrão visual para todos os slides", "Excluir slides", "Gravar áudio"] },
    { "id": 23, "difficulty": "hard", "q": "O que é 'Realidade Aumentada'?", "options": ["Ver o mundo em 3D", "Sobreposição de elementos virtuais à visão do mundo real", "Criação de um mundo totalmente virtual", "Aumento da tela do monitor"] },
    { "id": 24, "difficulty": "easy", "q": "O que significa 'Backup'?", "options": ["Reiniciar o PC", "Cópia de segurança dos dados", "Exclusão de arquivos", "Cabo de rede reserva"] },
    { "id": 25, "difficulty": "hard", "q": "Qual a principal característica de um 'Smartglass'?", "options": ["Proteção contra UV", "Exibição de informações em lentes transparentes", "Lente de aumento simples", "Sensor de temperatura"] },
    { "id": 26, "difficulty": "hard", "q": "O que é 'Edge Computing'?", "options": ["Computação na borda (processamento próximo à origem do dado)", "Computação apenas no centro da rede", "Uso de servidores lentos", "Desconexão total da internet"] },
    { "id": 27, "difficulty": "medium", "q": "No Excel, o símbolo '$' em uma fórmula (ex: $A$1) serve para:", "options": ["Indicar valor em dinheiro", "Fixar a referência da célula (referência absoluta)", "Somar valores", "Mudar a cor da célula"] },
    { "id": 28, "difficulty": "medium", "q": "O que é 'Cobot'?", "options": ["Robô gigante", "Robô colaborativo que trabalha junto ao humano", "Robô de combate", "Software de desenho"] },
    { "id": 29, "difficulty": "hard", "q": "Qual a função da GPU?", "options": ["Processar textos", "Processamento gráfico e cálculos paralelos", "Controlar o mouse", "Alimentar a placa-mãe"] },
    { "id": 30, "difficulty": "easy", "q": "Qual a unidade de medida da resistência elétrica?", "options": ["Volt", "Ohm", "Ampere", "Watt"] },
    { "id": 31, "difficulty": "easy", "q": "Pela Lei de Ohm, se aumentarmos a tensão em um resistor fixo, a corrente:", "options": ["Aumenta", "Diminui", "Permanece constante", "Inverte o sentido"] },
    { "id": 32, "difficulty": "medium", "q": "O que é um circuito em série?", "options": ["Vários caminhos para a corrente", "Apenas um caminho para a corrente", "Circuito desligado", "Circuito sem resistores"] },
    { "id": 33, "difficulty": "easy", "q": "Qual a unidade de medida da potência elétrica?", "options": ["Joule", "Watt", "Volt", "Hertz"] },
    { "id": 34, "difficulty": "medium", "q": "Um multímetro na função Ohmímetro deve ser usado com o circuito:", "options": ["Ligado", "Desenergizado", "Em curto-circuito", "Com carga máxima"] },
    { "id": 35, "difficulty": "medium", "q": "O que é Corrente Alternada (CA)?", "options": ["Corrente que flui em um só sentido", "Corrente que varia de sentido e magnitude periodicamente", "Corrente de bateria", "Corrente estática"] },
    { "id": 36, "difficulty": "easy", "q": "Qual a frequência da rede elétrica residencial no Brasil?", "options": ["50 Hz", "60 Hz", "100 Hz", "120 Hz"] },
    { "id": 37, "difficulty": "medium", "q": "O que é um Transformador?", "options": ["Dispositivo que converte CA em CC", "Dispositivo que altera níveis de tensão e corrente via eletromagnetismo", "Motor de alta rotação", "Sensor de calor"] },
    { "id": 38, "difficulty": "medium", "q": "Qual componente armazena energia em um campo elétrico?", "options": ["Resistor", "Capacitor", "Indutor", "Diodo"] },
    { "id": 39, "difficulty": "medium", "q": "Qual componente armazena energia em um campo magnético?", "options": ["Diodo", "Indutor", "Fusível", "Transistor"] },
    { "id": 40, "difficulty": "hard", "q": "O que acontece se ligarmos um capacitor eletrolítico com a polaridade invertida?", "options": ["Ele funciona melhor", "Ele pode explodir ou danificar-se", "A capacitância aumenta", "Nada acontece"] },
    { "id": 41, "difficulty": "easy", "q": "Qual a função do Diodo?", "options": ["Amplificar sinal", "Permitir a passagem de corrente em apenas um sentido", "Armazenar carga", "Regular temperatura"] },
    { "id": 42, "difficulty": "easy", "q": "O que é um LED?", "options": ["Lâmpada de calor", "Diodo Emissor de Luz", "Leitor Eletrónico de Dados", "Ligação Elétrica Direta"] },
    { "id": 43, "difficulty": "medium", "q": "O que faz um Transistor em modo de chaveamento?", "options": ["Varia a resistência continuamente", "Funciona como um interruptor eletrónico (Liga/Desliga)", "Converte calor em luz", "Mede pressão"] },
    { "id": 44, "difficulty": "medium", "q": "A Primeira Lei de Kirchhoff diz que:", "options": ["A soma das tensões em uma malha é zero", "A soma das correntes que entram em um nó é igual à que saem", "V = R.I", "P = V.I"] },
    { "id": 45, "difficulty": "medium", "q": "O que é o Efeito Joule?", "options": ["Transformação de luz em som", "Transformação de energia elétrica em calor", "Geração de magnetismo", "Resfriamento de condutores"] },
    { "id": 46, "difficulty": "easy", "q": "Qual o valor decimal do binário 1010?", "options": ["5", "10", "12", "15"] },
    { "id": 47, "difficulty": "medium", "q": "Qual porta lógica resulta em '1' apenas se todas as entradas forem '1'?", "options": ["OR", "AND", "NOT", "XOR"] },
    { "id": 48, "difficulty": "medium", "q": "Qual porta lógica resulta em '1' se qualquer uma das entradas for '1'?", "options": ["AND", "OR", "NAND", "NOR"] },
    { "id": 49, "difficulty": "hard", "q": "O que é um Osciloscópio?", "options": ["Mede apenas resistência", "Instrumento para visualizar formas de onda no tempo", "Gerador de energia", "Sensor de umidade"] },
    { "id": 50, "difficulty": "medium", "q": "Qual a função do retificador em ponte?", "options": ["Transformar CC em CA", "Transformar CA em CC (Onda completa)", "Cortar o sinal", "Filtrar ruídos"] },
    { "id": 51, "difficulty": "medium", "q": "Em um circuito paralelo de resistores, a tensão em cada resistor é:", "options": ["Diferente", "A mesma para todos", "Zero", "Depende da corrente"] },
    { "id": 52, "difficulty": "medium", "q": "O que significa 'RMS' em uma tensão alternada?", "options": ["Valor Máximo", "Valor Eficaz", "Valor Médio", "Valor de Pico"] },
    { "id": 53, "difficulty": "easy", "q": "Qual componente é usado para proteção contra sobrecorrente?", "options": ["Resistor", "Fusível", "Capacitor", "Pilha"] },
    { "id": 54, "difficulty": "hard", "q": "O que é um MOSFET?", "options": ["Um tipo de relé", "Um transistor de efeito de campo de metal-óxido-semicondutor", "Uma bateria", "Um sensor de luz"] },
    { "id": 55, "difficulty": "easy", "q": "Qual a base do sistema Hexadecimal?", "options": ["2", "10", "16", "8"] },
    { "id": 56, "difficulty": "hard", "q": "O que é um Flip-Flop?", "options": ["Um tipo de calçado", "Um circuito digital capaz de armazenar 1 bit", "Um motor de passo", "Um cabo de rede"] },
    { "id": 57, "difficulty": "medium", "q": "O que define o Fator de Potência?", "options": ["Relação entre potência ativa e aparente", "Soma das resistências", "Velocidade do motor", "Tensão da bateria"] },
    { "id": 58, "difficulty": "easy", "q": "Qual o símbolo químico do silício, principal material semicondutor?", "options": ["S", "Si", "Sl", "Sc"] },
    { "id": 59, "difficulty": "medium", "q": "O que é um curto-circuito?", "options": ["Circuitos com alta resistência", "Caminho de baixa resistência que desvia a corrente", "Circuito aberto", "Falta de bateria"] },
    { "id": 60, "difficulty": "easy", "q": "Qual a unidade de frequência?", "options": ["Henry", "Hertz", "Volt", "Ampere"] },
    { "id": 61, "difficulty": "hard", "q": "Em CA, a reatância capacitiva diminui quando a frequência:", "options": ["Aumenta", "Diminui", "Fica estável", "Zera"] },
    { "id": 62, "difficulty": "medium", "q": "O que é um Diodo Zener?", "options": ["Diodo que emite luz azul", "Diodo projetado para operar na região de ruptura (regulação)", "Diodo de alta potência", "Diodo que não conduz"] },
    { "id": 63, "difficulty": "hard", "q": "Qual o valor da constante de tempo em um circuito RC?", "options": ["R + C", "R * C", "R / C", "C / R"] },
    { "id": 64, "difficulty": "medium", "q": "O que é Indução Eletromagnética?", "options": ["Criação de calor pelo fio", "Geração de tensão em um condutor imerso em campo magnético variável", "Atração de plásticos", "Queima de fusível"] },
    { "id": 65, "difficulty": "hard", "q": "O que é um Amplificador Operacional (Op-Amp)?", "options": ["Motor elétrico", "Circuito integrado de alto ganho usado em processamento de sinais", "Bateria recarregável", "Chave magnética"] },
    { "id": 66, "difficulty": "hard", "q": "O que é um Tiristor (SCR)?", "options": ["Transistor de baixa potência", "Semicondutor que funciona como chave controlada para grandes cargas", "Resistor variável", "Capacitor de cerâmica"] },
    { "id": 67, "difficulty": "easy", "q": "Qual a função do 'GND' (Ground)?", "options": ["Aumentar a tensão", "Ponto de referência zero de um circuito", "Ligar o motor", "Medir a corrente"] },
    { "id": 68, "difficulty": "easy", "q": "No sistema binário, o que é um 'Byte'?", "options": ["1 bit", "4 bits", "8 bits", "16 bits"] },
    { "id": 69, "difficulty": "medium", "q": "O que é uma 'Tabela Verdade'?", "options": ["Lista de preços", "Tabela que mostra as saídas de um circuito lógico para todas as entradas", "Manual do fabricante", "Gráfico de temperatura"] },
    { "id": 70, "difficulty": "medium", "q": "O que é um Varistor?", "options": ["Resistor que varia com a luz", "Resistor que varia com a tensão (proteção contra surtos)", "Resistor de precisão", "Resistor térmico"] },
    { "id": 71, "difficulty": "hard", "q": "Qual a principal diferença entre MOSFET e BJT?", "options": ["Tamanho", "Controle por tensão vs controle por corrente", "Preço", "Cor"] },
    { "id": 72, "difficulty": "medium", "q": "O que é um Optoacoplador?", "options": ["Lente de aumento", "Componente que transfere sinais via luz, isolando eletricamente", "Conector de fibra ótica", "Sensor de movimento"] },
    { "id": 73, "difficulty": "easy", "q": "Qual a unidade de medida da indutância?", "options": ["Farad", "Henry", "Tesla", "Weber"] },
    { "id": 74, "difficulty": "hard", "q": "O que é Ressonância em circuitos RLC?", "options": ["Quando o circuito para", "Quando a reatância indutiva é igual à capacitiva", "Quando a bateria acaba", "Quando o resistor queima"] },
    { "id": 75, "difficulty": "medium", "q": "O que faz um Inversor (porta lógica)?", "options": ["Soma entradas", "Inverte o nível lógico (0 vira 1 e vice-versa)", "Multiplica sinais", "Gera pulsos"] },
    { "id": 76, "difficulty": "hard", "q": "Qual a tensão de pico de uma rede 220V RMS?", "options": ["220V", "311V", "110V", "440V"] },
    { "id": 77, "difficulty": "medium", "q": "O que é um Termistor NTC?", "options": ["Resistor que aumenta resistência com calor", "Resistor que diminui resistência com calor", "Resistor fixo", "Sensor de luz"] },
    { "id": 78, "difficulty": "hard", "q": "Qual a função de um capacitor de filtro em uma fonte?", "options": ["Aumentar a tensão", "Reduzir a oscilação (ripple) da tensão retificada", "Gerar CA", "Proteger contra curtos"] },
    { "id": 79, "difficulty": "hard", "q": "O que é um Gerador de Funções?", "options": ["Calculadora", "Equipamento que gera sinais elétricos (senoidal, quadrada, etc)", "Fonte de bancada", "Multímetro"] },
    { "id": 80, "difficulty": "easy", "q": "O que é o sistema BCD?", "options": ["Código de barras", "Decimal Codificado em Binário", "Protocolo de rede", "Tipo de bateria"] },
    { "id": 81, "difficulty": "hard", "q": "O que é um Multiplexador (MUX)?", "options": ["Inversor de tensão", "Dispositivo que seleciona uma de várias entradas para uma única saída", "Motor trifásico", "Cabo coaxial"] },
    { "id": 82, "difficulty": "medium", "q": "O que é a Lei de Faraday?", "options": ["Lei do calor", "Lei da indução eletromagnética", "Lei das correntes", "Lei da gravidade"] },
    { "id": 83, "difficulty": "medium", "q": "O que é um PWM?", "options": ["Modulação por largura de pulso", "Potência Watt Média", "Protocolo Web Mobile", "Placa de montagem"] },
    { "id": 84, "difficulty": "medium", "q": "Qual a cor do resistor de 1k Ohm (tolerância 5%)?", "options": ["Marrom, Preto, Vermelho, Ouro", "Marrom, Preto, Laranja, Ouro", "Vermelho, Vermelho, Vermelho, Ouro", "Preto, Marrom, Vermelho, Ouro"] },
    { "id": 85, "difficulty": "medium", "q": "O que é uma Matriz de Contatos (Protoboard)?", "options": ["Placa soldada", "Placa para prototipagem rápida sem solda", "Manual de esquemas", "Sensor de toque"] },
    { "id": 86, "difficulty": "hard", "q": "O que é Impedância?", "options": ["Apenas resistência", "Oposição total ao fluxo de CA (Resistência + Reatância)", "Tensão máxima", "Falta de corrente"] },
    { "id": 87, "difficulty": "medium", "q": "O que é um ADC?", "options": ["Conversor Analógico para Digital", "Alimentação de Corrente", "Aparelho de Carga", "Diodo de Calor"] },
    { "id": 88, "difficulty": "easy", "q": "O que é o código ASCII?", "options": ["Protocolo de internet", "Padrão de codificação de caracteres", "Desenho técnico", "Linguagem de PLC"] },
    { "id": 89, "difficulty": "medium", "q": "Qual componente é usado para 'ceifar' picos de tensão?", "options": ["Capacitor", "Diodo Zener", "Transformador", "Indutor"] },
    { "id": 90, "difficulty": "medium", "q": "O que é um sistema Trifásico?", "options": ["Um fio com 3 tensões", "Conjunto de três tensões alternadas defasadas de 120 graus", "Motor de 3 baterias", "Rede de alta frequência"] },
    { "id": 91, "difficulty": "easy", "q": "O que é a Tensão de Linha?", "options": ["Tensão entre fase e neutro", "Tensão entre duas fases", "Tensão do aterramento", "Tensão da bateria"] },
    { "id": 92, "difficulty": "medium", "q": "Qual a vantagem do sistema trifásico na indústria?", "options": ["Fios mais finos", "Motores mais eficientes e transmissão de potência constante", "Menos manutenção", "Cor azul dos cabos"] },
    { "id": 93, "difficulty": "easy", "q": "O que é a Potência Ativa?", "options": ["Potência que gera calor ou trabalho (Watts)", "Potência de reserva", "Potência dissipada no ar", "Potência reativa"] },
    { "id": 94, "difficulty": "easy", "q": "O que é a Potência Reativa?", "options": ["Potência útil", "Potência necessária para criar campos magnéticos (VAr)", "Potência da bateria", "Potência de luz"] },
    { "id": 95, "difficulty": "medium", "q": "Qual componente corrige o Fator de Potência?", "options": ["Resistor", "Banco de Capacitores", "Motor de passo", "Diodo"] },
    { "id": 96, "difficulty": "easy", "q": "O que é uma Bobina?", "options": ["Um pedaço de carvão", "Fio enrolado que cria campo magnético (Indutor)", "Tipo de capacitor", "Fusível"] },
    { "id": 97, "difficulty": "easy", "q": "O que é um Relé Eletromecânico?", "options": ["Interruptor manual", "Interruptor acionado por uma bobina eletromagnética", "Motor DC", "Sensor ótico"] },
    { "id": 98, "difficulty": "medium", "q": "O que é a Lei de Lenz?", "options": ["Lei do som", "Lei que diz que o sentido da corrente induzida se opõe à variação do fluxo", "Lei da gravidade", "Lei térmica"] },
    { "id": 99, "difficulty": "easy", "q": "Qual a cor padrão do condutor Neutro conforme NBR 5410?", "options": ["Verde", "Azul Claro", "Preto", "Vermelho"] },
    { "id": 100, "difficulty": "easy", "q": "Qual função do Arduino roda apenas uma vez no início?", "options": ["loop()", "setup()", "main()", "start()"] },
    { "id": 101, "difficulty": "easy", "q": "Qual função do Arduino executa repetidamente?", "options": ["setup()", "loop()", "repeat()", "cycle()"] },
    { "id": 102, "difficulty": "easy", "q": "Como declarar o pino 13 como saída no Arduino?", "options": ["pinMode(13, INPUT)", "pinMode(13, OUTPUT)", "digitalWrite(13, HIGH)", "analogWrite(13, 255)"] },
    { "id": 103, "difficulty": "easy", "q": "Qual comando lê um sinal digital (0 ou 1) em um pino?", "options": ["analogRead()", "digitalRead()", "pinRead()", "readDigital()"] },
    { "id": 104, "difficulty": "medium", "q": "Qual comando envia um valor PWM (0 a 255) para um pino?", "options": ["digitalWrite()", "analogWrite()", "pwmWrite()", "analogRead()"] },
    { "id": 105, "difficulty": "easy", "q": "O que faz o comando 'Serial.begin(9600)'?", "options": ["Liga o motor", "Inicia a comunicação serial a 9600 bps", "Define o brilho", "Limpa a tela"] },
    { "id": 106, "difficulty": "medium", "q": "Qual o valor máximo retornado por 'analogRead()'?", "options": ["255", "1023", "5", "100"] },
    { "id": 107, "difficulty": "easy", "q": "O que significa 'HIGH' em um pino digital de 5V?", "options": ["0V", "5V", "2.5V", "Desligado"] },
    { "id": 108, "difficulty": "easy", "q": "Para que serve o comando 'delay(500)'?", "options": ["Pausa o código por 500 segundos", "Pausa o código por 500 milissegundos", "Aumenta a velocidade", "Muda o pino"] },
    { "id": 109, "difficulty": "medium", "q": "Qual the operador de 'E lógico' em C++?", "options": ["||", "&&", "!", "=="] },
    { "id": 110, "difficulty": "medium", "q": "Qual the operador de 'OU lógico' em C++?", "options": ["&&", "||", "??", "!="] },
    { "id": 111, "difficulty": "easy", "q": "Como comentar uma linha no código Arduino?", "options": ["# comentário", "// comentário", "/* comentário", "-- comentário"] },
    { "id": 112, "difficulty": "easy", "q": "O que acontece se esquecer o ';' ao final de uma linha?", "options": ["Nada", "Erro de compilação", "O Arduino explode", "O motor gira lento"] },
    { "id": 113, "difficulty": "medium", "q": "Qual tipo de variável armazena apenas 'true' ou 'false'?", "options": ["int", "float", "boolean", "String"] },
    { "id": 114, "difficulty": "medium", "q": "O que faz o comando 'digitalWrite(10, LOW)'?", "options": ["Liga o pino 10", "Desliga (0V) o pino 10", "Muda para entrada", "Lê o valor"] },
    { "id": 115, "difficulty": "medium", "q": "O que é 'PWM'?", "options": ["Potência Máxima", "Modulação por Largura de Pulso", "Protocolo de Rede", "Motor de Passo"] },
    { "id": 116, "difficulty": "medium", "q": "Como comparar se duas variáveis são iguais?", "options": ["=", "==", "===", "equals"] },
    { "id": 117, "difficulty": "medium", "q": "Para que serve a biblioteca '#include <Servo.h>'?", "options": ["Controlar LEDs", "Controlar Servo Motores", "Ligar o LCD", "Ligar Wi-Fi"] },
    { "id": 118, "difficulty": "hard", "q": "O que faz a função 'map(valor, 0, 1023, 0, 255)'?", "options": ["Cria um mapa", "Converte proporcionalmente uma escala em outra", "Desenha no LCD", "Inverte o pino"] },
    { "id": 119, "difficulty": "medium", "q": "Qual a finalidade do Monitor Serial?", "options": ["Ver vídeos", "Trocar dados entre PC e Arduino para depuração", "Programar a placa", "Medir tensão"] },
    { "id": 120, "difficulty": "easy", "q": "O que é um 'void' em uma função?", "options": ["Um erro", "Indica que a função não retorna valor", "Uma variável vazia", "O nome do loop"] },
    { "id": 121, "difficulty": "medium", "q": "O que faz o comando 'if(botao == HIGH) { ... }'?", "options": ["Repete o código", "Executa o bloco apenas se a condição for verdadeira", "Define o pino", "Apaga o código"] },
    { "id": 122, "difficulty": "easy", "q": "O que é uma 'String' no código?", "options": ["Um número", "Uma cadeia de caracteres (texto)", "Um tipo de pino", "Uma cor"] },
    { "id": 123, "difficulty": "hard", "q": "Qual pino do Arduino Uno suporta PWM?", "options": ["Pino 2", "Pino 3", "Pino 4", "Pino 7"] },
    { "id": 124, "difficulty": "easy", "q": "Como incrementar a variável 'cont' em 1?", "options": ["cont + 1", "cont++", "cont = 1", "inc(cont)"] },
    { "id": 125, "difficulty": "medium", "q": "O que faz o comando 'else { ... }'?", "options": ["Repete o 'if'", "Executa se a condição do 'if' for falsa", "Para o código", "Lê sensores"] },
    { "id": 126, "difficulty": "hard", "q": "Qual comando lê a temperatura de um DHT11 (usando biblioteca)?", "options": ["dht.read()", "dht.readTemperature()", "analogRead(A0)", "digitalRead(2)"] },
    { "id": 127, "difficulty": "medium", "q": "O que é o 'Baud Rate'?", "options": ["Velocidade do motor", "Velocidade de transmissão serial (bits por segundo)", "Brilho do LED", "Tempo de delay"] },
    { "id": 128, "difficulty": "hard", "q": "Como declarar um array de 3 inteiros?", "options": ["int x = 3", "int x[3]", "array x(3)", "list x[3]"] },
    { "id": 129, "difficulty": "medium", "q": "O que faz 'Serial.println(\"Oi\")'?", "options": ["Escreve 'Oi' e pula linha", "Apaga o texto", "Escreve 'Oi' sem pular linha", "Manda para o motor"] },
    { "id": 130, "difficulty": "easy", "q": "Qual o primeiro índice de um array em C++?", "options": ["1", "0", "-1", "Depende"] },
    { "id": 131, "difficulty": "hard", "q": "Para que serve a estrutura 'for(int i=0; i<10; i++)'?", "options": ["Testar condição", "Repetir um bloco 10 vezes", "Criar um delay", "Configurar pinos"] },
    { "id": 132, "difficulty": "medium", "q": "O que é 'Input Pullup'?", "options": ["Pino de saída forte", "Entrada com resistor interno ligado ao 5V", "Pino de alta voltagem", "Desligar o pino"] },
    { "id": 133, "difficulty": "hard", "q": "Qual comando lê a distância de um sensor ultrassônico?", "options": ["digitalRead()", "pulseIn() no pino Echo", "analogRead()", "readDistance()"] },
    { "id": 134, "difficulty": "medium", "q": "Como declarar uma constante em C++?", "options": ["var x = 10", "const int x = 10", "fix x = 10", "let x = 10"] },
    { "id": 135, "difficulty": "hard", "q": "O que faz o operador '!' (ex: !estado)?", "options": ["Soma 1", "Inverte o valor lógico (NÃO)", "Confirma o valor", "Deleta o valor"] },
    { "id": 136, "difficulty": "medium", "q": "Qual tipo de variável armazena um único caractere?", "options": ["int", "char", "String", "byte"] },
    { "id": 137, "difficulty": "hard", "q": "Para que serve 'switch(x) { case 1: ... }'?", "options": ["Repetir código", "Selecionar um bloco entre várias opções", "Criar variáveis", "Mudar o pino"] },
    { "id": 138, "difficulty": "medium", "q": "O que faz 'float temp = 25.5'?", "options": ["Armazena texto", "Armazena número com casa decimal", "Armazena inteiro", "Armazena cor"] },
    { "id": 139, "difficulty": "hard", "q": "O que é 'Debounce' em botões?", "options": ["Apertar forte", "Técnica para ignorar ruídos elétricos no clique", "Ligar no GND", "Mudar de cor"] },
    { "id": 140, "difficulty": "hard", "q": "Como encerrar um loop 'for' prematuramente?", "options": ["stop", "break", "exit", "return"] },
    { "id": 141, "difficulty": "hard", "q": "O que faz 'pow(2, 3)'?", "options": ["Soma 2 e 3", "Calcula 2 elevado a 3", "Multiplica 2 por 3", "Divide 2 por 3"] },
    { "id": 142, "difficulty": "medium", "q": "Para que serve 'random(1, 10)'?", "options": ["Lê sensor", "Gera um número aleatório entre 1 e 9", "Define o brilho", "Pausa o código"] },
    { "id": 143, "difficulty": "easy", "q": "O que é o 'Arduino IDE'?", "options": ["A placa física", "O software usado para escrever e carregar o código", "Um tipo de sensor", "Um cabo USB"] },
    { "id": 144, "difficulty": "medium", "q": "O que faz o botão 'Verify' na IDE?", "options": ["Manda para a placa", "Compila e verifica erros no código", "Apaga o código", "Formata o PC"] },
    { "id": 145, "difficulty": "medium", "q": "O que faz o botão 'Upload' na IDE?", "options": ["Salva no Google Drive", "Compila e envia o programa para o Arduino", "Reinicia a placa", "Abre o monitor serial"] },
    { "id": 146, "difficulty": "hard", "q": "Qual biblioteca controla telas LCD via I2C?", "options": ["<LCD.h>", "<LiquidCrystal_I2C.h>", "<Display.h>", "<Screen.h>"] },
    { "id": 147, "difficulty": "medium", "q": "Como limpar a tela do LCD?", "options": ["lcd.clear()", "lcd.clean()", "lcd.reset()", "lcd.delete()"] },
    { "id": 148, "difficulty": "hard", "q": "O que faz 'lcd.setCursor(0, 1)'?", "options": ["Escreve 0 e 1", "Posiciona o cursor na coluna 0, linha 1 (2ª linha)", "Limpa a linha 1", "Define o brilho"] },
    { "id": 149, "difficulty": "hard", "q": "Qual o limite de memória flash do Arduino Uno?", "options": ["1 TB", "32 KB", "4 GB", "1 MB"] },
    { "id": 150, "difficulty": "easy", "q": "Qual a principal finalidade da norma NR-12?", "options": ["Economia de energia", "Segurança no trabalho em máquinas e equipamentos", "Pintura industrial", "Treinamento de RH"] },
    { "id": 151, "difficulty": "easy", "q": "O que é um Botão de Emergência?", "options": ["Botão de ligar", "Dispositivo de parada imediata com trava mecânica", "Campainha", "Reset do PC"] },
    { "id": 152, "difficulty": "hard", "q": "Para que serve a Cortina de Luz na NR-12?", "options": ["Decorar a fábrica", "Detectar a intrusão de membros em áreas de risco", "Iluminar o painel", "Bloquear o sol"] },
    { "id": 153, "difficulty": "medium", "q": "O que é um Relé de Segurança?", "options": ["Relé comum", "Relé com redundância para monitorar dispositivos de parada", "Relé de luz", "Relé de tempo"] },
    { "id": 154, "difficulty": "easy", "q": "Qual a cor padrão do condutor de Aterramento (PE)?", "options": ["Azul", "Verde ou Verde-Amarelo", "Preto", "Branco"] },
    { "id": 155, "difficulty": "medium", "q": "O que é um Sensor Indutivo?", "options": ["Detecta plástico", "Detecta objetos metálicos sem contato", "Mede calor", "Mede som"] },
    { "id": 156, "difficulty": "medium", "q": "O que é um Sensor Capacitivo?", "options": ["Detecta apenas metal", "Detecta diversos materiais (metais, líquidos, grãos)", "Sensor de rádio", "Sensor de luz"] },
    { "id": 157, "difficulty": "hard", "q": "Para que serve um Inversor de Frequência?", "options": ["Carregar bateria", "Controlar velocidade e torque de motores AC", "Aumentar a tensão", "Inverter a cor"] },
    { "id": 158, "difficulty": "medium", "q": "O que é um Motor de Passo?", "options": ["Motor de alta velocidade", "Motor que se move em incrementos discretos (passos)", "Motor a diesel", "Motor de polia"] },
    { "id": 159, "difficulty": "medium", "q": "O que é um Servo Motor?", "options": ["Motor comum", "Motor de alta precisão com feedback de posição", "Motor de 12V", "Gerador"] },
    { "id": 160, "difficulty": "medium", "q": "O que faz uma Válvula Solenoide?", "options": ["Mede pressão", "Controlar o fluxo de ar/fluido via sinal elétrico", "Filtra o ar", "Gera vácuo"] },
    { "id": 161, "difficulty": "medium", "q": "O que é um Atuador Pneumático?", "options": ["Motor elétrico", "Dispositivo que transforma energia do ar em movimento", "Bomba de água", "Válvula manual"] },
    { "id": 162, "difficulty": "medium", "q": "Para que serve o conjunto FRL?", "options": ["Ligar o motor", "Filtro, Regulador e Lubrificador de ar comprimido", "Medir energia", "Sensor de luz"] },
    { "id": 163, "difficulty": "hard", "q": "O que é a Manutenção Preditiva?", "options": ["Consertar após quebrar", "Monitoramento para prever falhas antes que ocorram", "Troca agendada", "Limpeza"] },
    { "id": 164, "difficulty": "medium", "q": "O que é a Manutenção Preventiva?", "options": ["Consertar após quebrar", "Intervenções agendadas para evitar falhas", "Pintura", "Troca de óleo"] },
    { "id": 165, "difficulty": "medium", "q": "O que é um Contator?", "options": ["Calculadora", "Chave eletromecânica para manobra de motores", "Sensor", "Fusível"] },
    { "id": 166, "difficulty": "easy", "q": "Para que serve o Relé Térmico?", "options": ["Medir calor", "Proteger o motor contra sobrecarga", "Ligar lâmpada", "Contar peças"] },
    { "id": 167, "difficulty": "hard", "q": "O que é um Disjuntor Motor?", "options": ["Motor pequeno", "Dispositivo de proteção térmica e magnética para motores", "Sensor", "Botão"] },
    { "id": 168, "difficulty": "hard", "q": "Qual a função do Soft-Starter?", "options": ["Partida rápida", "Partida suave de motores para evitar picos de corrente", "Software", "Sensor"] },
    { "id": 169, "difficulty": "medium", "q": "O que é um Diagrama de Potência?", "options": ["Lista de nomes", "Desenho da parte de força de um sistema elétrico", "Gráfico de vendas", "Foto"] },
    { "id": 170, "difficulty": "medium", "q": "O que é um Diagrama de Comando?", "options": ["Foto do painel", "Desenho da lógica de controle de um sistema", "Manual de uso", "Planilha"] },
    { "id": 171, "difficulty": "easy", "q": "O que é um Borne?", "options": ["Um parafuso", "Ponto de conexão para fios dentro de um painel", "Tipo de sensor", "Motor"] },
    { "id": 172, "difficulty": "medium", "q": "Para que serve a Anilha na instalação?", "options": ["Isolar o fio", "Identificar os cabos conforme o projeto", "Amarrar fios", "Pintar"] },
    { "id": 173, "difficulty": "medium", "q": "O que é um Terminal Ilhós?", "options": ["Um furo", "Terminal crimpado para garantir bom contato elétrico", "Pilha", "Sensor"] },
    { "id": 174, "difficulty": "easy", "q": "O que é um Manômetro?", "options": ["Mede calor", "Mede pressão de fluidos", "Mede som", "Mede luz"] },
    { "id": 175, "difficulty": "medium", "q": "O que faz a Válvula 3/2 vias?", "options": ["Tem 3 vias e 2 posições", "Tem 2 vias e 3 posições", "Mede pressão", "Liga 3 motores"] },
    { "id": 176, "difficulty": "easy", "q": "O que é um Trilho DIN?", "options": ["Pista de corrida", "Suporte metálico padrão para fixar componentes no painel", "Cabo de rede", "Mangueira"] },
    { "id": 177, "difficulty": "medium", "q": "Para que serve a Canaleta no painel?", "options": ["Drenar água", "Organizar e conduzir a fiação internamente", "Proteger contra sol", "Esfriar"] },
    { "id": 178, "difficulty": "medium", "q": "O que é uma Prensa-Cabo?", "options": ["Um alicate", "Acessório para fixar e vedar a entrada de cabos no painel", "Ferramenta", "Terminal"] },
    { "id": 179, "difficulty": "hard", "q": "O que é o Intertravamento Elétrico?", "options": ["Trancar o painel", "Lógica que impede o acionamento simultâneo de dispositivos", "Troca de fios", "Curto"] },
    { "id": 180, "difficulty": "easy", "q": "Para que serve o Multímetro na manutenção?", "options": ["Medir peças", "Medir tensão, corrente e resistência", "Aparafusar", "Limpar"] },
    { "id": 181, "difficulty": "medium", "q": "O que é um Termostato?", "options": ["Motor", "Dispositivo que controla a temperatura", "Sensor ótico", "Fusível"] },
    { "id": 182, "difficulty": "medium", "q": "O que é um Sensor de Proximidade Ótico?", "options": ["Detecta som", "Detecta objetos via luz (infravermelho/laser)", "Detecta metal", "Mede peso"] },
    { "id": 183, "difficulty": "hard", "q": "O que é a Carga de Trabalho em ergonomia?", "options": ["Peso das caixas", "Esforço físico e mental exigido do trabalhador", "Preço do serviço", "Horas extras"] },
    { "id": 184, "difficulty": "easy", "q": "Qual a função do Fusível?", "options": ["Aumentar tensão", "Proteger contra curto-circuito (rompe o filamento)", "Ligar luz", "Sensor"] },
    { "id": 185, "difficulty": "hard", "q": "O que é um Encoder na manutenção?", "options": ["Computador", "Sensor que informa a posição rotativa do motor", "Válvula", "Motor"] },
    { "id": 186, "difficulty": "easy", "q": "O que é um Engate Rápido?", "options": ["Cabo USB", "Conexão rápida para mangueiras pneumáticas", "Pilha", "Botão"] },
    { "id": 187, "difficulty": "medium", "q": "O que faz o Regulador de Pressão?", "options": ["Aumenta o fluxo", "Mantém a pressão de saída estável e ajustada", "Corta o ar", "Gera som"] },
    { "id": 188, "difficulty": "hard", "q": "O que é um Diagrama Unifilar?", "options": ["Muitos fios", "Representação simplificada com uma linha para o sistema", "Foto", "Manual"] },
    { "id": 189, "difficulty": "medium", "q": "O que é a Ordem de Serviço (OS)?", "options": ["Nota fiscal", "Documento que autoriza e descreve a tarefa de manutenção", "Lista de nomes", "Regra"] },
    { "id": 190, "difficulty": "medium", "q": "Para que serve a Lubrificação no ar comprimido?", "options": ["Gerar energia", "Reduzir atrito e desgaste em cilindros e válvulas", "Mudar a cor", "Limpar"] },
    { "id": 191, "difficulty": "medium", "q": "O que é um CLP Compacto?", "options": ["CLP gigante", "CLP com entradas e saídas fixas no corpo", "CLP de papel", "Pilha"] },
    { "id": 192, "difficulty": "medium", "q": "O que é uma IHM?", "options": ["Interface de Hardware", "Interface Homem-Máquina (tela de controle)", "Impressora", "Motor"] },
    { "id": 193, "difficulty": "easy", "q": "O que é Manutenção Corretiva?", "options": ["Evitar falhas", "Intervenção após a ocorrência da falha", "Pintura", "Troca agendada"] },
    { "id": 194, "difficulty": "easy", "q": "Para que serve a NR-10?", "options": ["Segurança em Altura", "Segurança em instalações e serviços em eletricidade", "Pintura", "EPI"] },
    { "id": 195, "difficulty": "easy", "q": "O que é o EPI?", "options": ["Equipamento de Proteção Individual", "Escola de Programação", "Empresa de Instalação", "Placa"] },
    { "id": 196, "difficulty": "easy", "q": "O que é o EPC?", "options": ["Equipamento de Proteção Coletiva", "Empresa de Controle", "Plano de Carga", "Sensor"] },
    { "id": 197, "difficulty": "easy", "q": "Qual a função do aterramento?", "options": ["Aumentar a conta", "Segurança contra choques e proteção de equipamentos", "Ligar lâmpada", "Mudar fase"] },
    { "id": 198, "difficulty": "medium", "q": "O que é um Multímetro CAT III?", "options": ["Categoria de peso", "Categoria de segurança para medições industriais", "Cor do multímetro", "Preço"] },
    { "id": 199, "difficulty": "easy", "q": "O que é um Checklist?", "options": ["Lista de compras", "Lista de verificação para garantir que nada foi esquecido", "Foto", "Manual"] }
];
